// <auto-generated />
using Laboratorna_3_pz;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Laboratorna_3_pz.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221002102150_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("Laboratorna_3_pz.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Product_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Product_Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Product_Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Product_Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
